# Generated by Django 4.0.3 on 2022-09-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('Ad_id', models.AutoField(primary_key=True, serialize=False, verbose_name='管理员ID')),
                ('Ad_name', models.CharField(max_length=20, verbose_name='管理员名')),
                ('Ad_password', models.CharField(max_length=30, verbose_name='管理员密码')),
            ],
        ),
        migrations.CreateModel(
            name='Answer_data',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False, verbose_name='特定数据id')),
                ('key_words', models.CharField(max_length=30, verbose_name='关键字')),
                ('reply', models.CharField(max_length=100, verbose_name='回复文字')),
                ('user_image', models.ImageField(null=True, upload_to='media/', verbose_name='图片')),
                ('url', models.CharField(max_length=100, verbose_name='超链接')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(max_length=30, verbose_name='用户IP')),
                ('user_brower', models.CharField(max_length=500, verbose_name='用户浏览器类型')),
                ('date', models.DateTimeField(verbose_name='用户上线时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('user_sex', models.IntegerField(choices=[(0, '女性'), (1, '男性')], default=1)),
                ('user_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('user_password', models.CharField(max_length=30, verbose_name='用户密码')),
                ('user_phone', models.CharField(max_length=20, verbose_name='用户电话号码')),
                ('user_email', models.EmailField(max_length=30, null=True, verbose_name='用户邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='输入数据id')),
                ('words', models.CharField(max_length=30, verbose_name='用户输入的文字')),
                ('image', models.ImageField(upload_to='upload/', verbose_name='用户上传的图片')),
            ],
        ),
    ]
